### PR TITLE
Service logs are build artifacts

### PR DESCRIPTION
**Pull request by houli**
Also remove parallel because it was unnecessary and p much same time to build

### CODE REVIEW

**Review by c-brenn — APPROVED** [review]
🚢 🐳

**Comment by c-brenn** [comment]
how much time are we saving by running the e2e tests in the background?

**Comment by houli** [comment]
I would say about 30 seconds but then again the time taken for panacea tests seems to have increased about 30 seconds from what it used to be

**Comment by houli** [comment]
So, possibly 0

**Comment by c-brenn** [comment]
ye, not sure if anything is actually happening in parallel. I'd be up for just running normally

**Comment by houli** [comment]
Testing with that last commit, will see how it goes then off to bed

**Pull request merged**
